/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package francisleysalla.tipovoto;

import java.util.Calendar;
/**
 *
 * @author Francisco
 */
public class TelaVoto extends javax.swing.JFrame {
    Calendar schedule = Calendar.getInstance();
    int year = schedule.get(Calendar.YEAR);
    int month = schedule.get(Calendar.MONTH) + 1;
    int day = schedule.get(Calendar.DAY_OF_MONTH);

    /**
     * Creates new form TelaVoto
     */
    public TelaVoto() {
        
        initComponents();
        panOut.setVisible(false);
        spnYear.setModel(new javax.swing.SpinnerNumberModel(2000, 1900, year, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnDay = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spnMonth = new javax.swing.JSpinner();
        spnYear = new javax.swing.JSpinner();
        panOut = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblOutAge = new javax.swing.JLabel();
        lblOutSit = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Possibilidade de voto");
        setResizable(false);

        spnDay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        spnDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Digite sua data de nascimento:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("/");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("/");

        spnMonth.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        spnMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnYear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("A sua idade é:");

        lblOutAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblOutAge.setForeground(new java.awt.Color(0, 0, 255));
        lblOutAge.setText("idade");

        lblOutSit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOutSit.setForeground(new java.awt.Color(0, 0, 255));
        lblOutSit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutSit.setText("Situação");

        javax.swing.GroupLayout panOutLayout = new javax.swing.GroupLayout(panOut);
        panOut.setLayout(panOutLayout);
        panOutLayout.setHorizontalGroup(
            panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOutLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOutAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblOutSit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panOutLayout.setVerticalGroup(
            panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOutLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblOutAge))
                .addGap(20, 20, 20)
                .addComponent(lblOutSit)
                .addGap(0, 0, 0))
        );

        btnVer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnVer.setText("Eu posso votar?");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spnDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVer)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnYear))))
                    .addComponent(panOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(spnMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(btnVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(panOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        // Get the birth date
        int bDay = Integer.parseInt(spnDay.getValue().toString());
        int bMonth = Integer.parseInt(spnMonth.getValue().toString());
        int bYear = Integer.parseInt(spnYear.getValue().toString());
        
        /*
        Calculating the age. Possible cases:
        1 - Mes atual ser maior = Diferença dos anos
        2 - Mes atual ser menor = Diferença dos anos -1
        3 - Mes igual e dia atual maior ou igual = Diferença dos anos
        4 - Mes igual e dia atual menor = Diferença dos anos -1
        */
        int age = (month>bMonth)||(month == bMonth && day >= bDay)?year-bYear:year-bYear-1;
        lblOutAge.setText(Integer.toString(age));
        //Testing the age
        if (age >= 18 && age < 70){
            //Obrigatório
            lblOutSit.setText("O seu voto é obrigatório");
        }else if (age >= 16){
                //Opcional
                lblOutSit.setText("O seu voto é opcional");
            }else{
                //Não pode votar
                lblOutSit.setText("Você não pode votar");
            }
        
        //Show the results
        panOut.setVisible(true);
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblOutAge;
    private javax.swing.JLabel lblOutSit;
    private javax.swing.JPanel panOut;
    private javax.swing.JSpinner spnDay;
    private javax.swing.JSpinner spnMonth;
    private javax.swing.JSpinner spnYear;
    // End of variables declaration//GEN-END:variables
}
