/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package francisleysalla.classmath;

/**
 *
 * @author Francisco
 */
public class MainJFrame extends javax.swing.JFrame {
    double n1;
    int n2;
    double n3;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setRandomValues();
        calculateValues();
    }
    public void setRandomValues(){
        //A number between 0 and 1
        n1 = Math.random();
        //A number between 1 and 100
        n2 = (int)(1+ Math.random()*(100-1));
        //A negative number
        n3 = -(Math.random());
        //Setting the values in the labels
        number1.setText(Double.toString(n1));
        number2.setText(Integer.toString(n2));
        number3.setText(Double.toString(n3));
        power.setText(n1 + " elevado a "+n2+" é:");
        sqrt.setText("Raiz quadrada de "+n1+" é:");
        cbrt.setText("Raiz cúbica de "+n2+" é:");
        abs.setText("Valor absoluto de "+n3+" é:");
        round.setText(n1+" arredondado normalmente é:");
        ceil.setText(n1+" arredondado para cima é:");
        floor.setText(n1+" arredondado para baixo é:");
        pi.setText(n2+" X PI é:");
    }
    
    public void calculateValues(){
        power();
        sqrt();
        cbrt();
        abs();
        round();
        ceil();
        floor();
        pi();
    }
    private void power(){
        double n = Math.pow(n2,n1);
        outPower.setText(Double.toString(n));
    }
    private void sqrt(){
        double n = Math.sqrt(n1);
        outSqrt.setText(Double.toString(n));
    }
    private void cbrt(){
        double n = Math.cbrt(n2);
        outCbrt.setText(Double.toString(n));
    }
    private void abs(){
        double n = Math.abs(n3);
        outAbs.setText(Double.toString(n));
    }
    private void round(){
        double n = Math.round(n1);
        outRound.setText(Double.toString(n));
    }
    private void ceil(){
        double n = Math.ceil(n1);
        outCeil.setText(Double.toString(n));
    }
    private void floor(){
        double n = Math.floor(n1);
        outFloor.setText(Double.toString(n));
    }
    private void pi(){
        double piV = Math.PI;
        double n = piV*n2;
        outPi.setText(Double.toString(n));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desc1 = new javax.swing.JLabel();
        number1 = new javax.swing.JLabel();
        desc2 = new javax.swing.JLabel();
        number2 = new javax.swing.JLabel();
        power = new javax.swing.JLabel();
        outPower = new javax.swing.JLabel();
        sqrt = new javax.swing.JLabel();
        outSqrt = new javax.swing.JLabel();
        cbrt = new javax.swing.JLabel();
        outCbrt = new javax.swing.JLabel();
        abs = new javax.swing.JLabel();
        outAbs = new javax.swing.JLabel();
        round = new javax.swing.JLabel();
        outRound = new javax.swing.JLabel();
        ceil = new javax.swing.JLabel();
        outCeil = new javax.swing.JLabel();
        floor = new javax.swing.JLabel();
        outFloor = new javax.swing.JLabel();
        pi = new javax.swing.JLabel();
        outPi = new javax.swing.JLabel();
        btnAction = new javax.swing.JButton();
        desc3 = new javax.swing.JLabel();
        number3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Random Number Generator");
        setResizable(false);

        desc1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        desc1.setText("O primeiro número é:");

        number1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        number1.setText("0");
        number1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        desc2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        desc2.setText("O segundo número é:");

        number2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        number2.setText("0");
        number2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        power.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        power.setText("n2 elevado a n1 é:");

        outPower.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outPower.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outPower.setText("0");
        outPower.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        sqrt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sqrt.setText("Raiz quadrada de n1 é:");

        outSqrt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outSqrt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outSqrt.setText("0");
        outSqrt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cbrt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbrt.setText("Raiz cúbica de n2 é:");

        outCbrt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outCbrt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outCbrt.setText("0");
        outCbrt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        abs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        abs.setText("Valor absoluto de n3 é:");

        outAbs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outAbs.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outAbs.setText("0");
        outAbs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        round.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        round.setText("n2 arredondado normalmente é:");

        outRound.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outRound.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outRound.setText("0");
        outRound.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        ceil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ceil.setText("n1 arredondado para cima é:");

        outCeil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outCeil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outCeil.setText("0");
        outCeil.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        floor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        floor.setText("n1 arredondado para baixo é:");

        outFloor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outFloor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outFloor.setText("0");
        outFloor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        pi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pi.setText("n2 X PI é:");

        outPi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        outPi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outPi.setText("0");
        outPi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnAction.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnAction.setText("Novos números");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });

        desc3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        desc3.setText("O terceiro número é:");

        number3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        number3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        number3.setText("0");
        number3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor)
                            .addComponent(ceil)
                            .addComponent(abs)
                            .addComponent(cbrt)
                            .addComponent(sqrt)
                            .addComponent(power)
                            .addComponent(round)
                            .addComponent(pi)
                            .addComponent(desc2)
                            .addComponent(desc3)
                            .addComponent(desc1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outPi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outCeil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outPower, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outRound, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desc1)
                    .addComponent(number1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desc2)
                    .addComponent(number2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desc3)
                    .addComponent(number3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(power)
                    .addComponent(outPower))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqrt)
                    .addComponent(outSqrt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbrt)
                    .addComponent(outCbrt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abs)
                    .addComponent(outAbs))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(round)
                    .addComponent(outRound))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceil)
                    .addComponent(outCeil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floor)
                    .addComponent(outFloor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outPi)
                    .addComponent(pi))
                .addGap(18, 18, 18)
                .addComponent(btnAction)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        // TODO add your handling code here:
        setRandomValues();
        calculateValues();
    }//GEN-LAST:event_btnActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abs;
    private javax.swing.JButton btnAction;
    private javax.swing.JLabel cbrt;
    private javax.swing.JLabel ceil;
    private javax.swing.JLabel desc1;
    private javax.swing.JLabel desc2;
    private javax.swing.JLabel desc3;
    private javax.swing.JLabel floor;
    private javax.swing.JLabel number1;
    private javax.swing.JLabel number2;
    private javax.swing.JLabel number3;
    private javax.swing.JLabel outAbs;
    private javax.swing.JLabel outCbrt;
    private javax.swing.JLabel outCeil;
    private javax.swing.JLabel outFloor;
    private javax.swing.JLabel outPi;
    private javax.swing.JLabel outPower;
    private javax.swing.JLabel outRound;
    private javax.swing.JLabel outSqrt;
    private javax.swing.JLabel pi;
    private javax.swing.JLabel power;
    private javax.swing.JLabel round;
    private javax.swing.JLabel sqrt;
    // End of variables declaration//GEN-END:variables
}
