/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package francisleysalla.formulaquadratica;

/**
 *
 * @author Francisco
 */
public class CalculatorScreen extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorScreen
     */
    public CalculatorScreen() {
        initComponents();
        panOut.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panOut = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblOutDesc = new javax.swing.JLabel();
        lblOutPos = new javax.swing.JLabel();
        lblOutNeg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblExA = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblExB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblExC = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        numA = new javax.swing.JSpinner();
        numB = new javax.swing.JSpinner();
        numC = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Bhaskara");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora de fórmulas quadráticas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Exemplo:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("A:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Raiz positiva:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Raiz negativa:");

        lblOutDesc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblOutDesc.setForeground(new java.awt.Color(152, 0, 0));
        lblOutDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutDesc.setText("Quantas raízes a equação tem");

        lblOutPos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblOutPos.setForeground(new java.awt.Color(152, 0, 0));
        lblOutPos.setText("A raiz");

        lblOutNeg.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblOutNeg.setForeground(new java.awt.Color(152, 0, 0));
        lblOutNeg.setText("A raiz");

        javax.swing.GroupLayout panOutLayout = new javax.swing.GroupLayout(panOut);
        panOut.setLayout(panOutLayout);
        panOutLayout.setHorizontalGroup(
            panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOutDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panOutLayout.createSequentialGroup()
                .addGroup(panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOutPos, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(lblOutNeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panOutLayout.setVerticalGroup(
            panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOutLayout.createSequentialGroup()
                .addGroup(panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panOutLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6))
                    .addGroup(panOutLayout.createSequentialGroup()
                        .addGroup(panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblOutPos, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblOutNeg))))
                .addGap(18, 18, 18)
                .addComponent(lblOutDesc))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("B:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("C:");

        lblExA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblExA.setForeground(new java.awt.Color(152, 0, 0));
        lblExA.setText("A");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("x² +");

        lblExB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblExB.setForeground(new java.awt.Color(152, 0, 0));
        lblExB.setText("B");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("x + ");

        lblExC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblExC.setForeground(new java.awt.Color(152, 0, 0));
        lblExC.setText("C");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText(" = 0");

        btnCalc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        numA.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        numA.setModel(new javax.swing.SpinnerNumberModel(0, -100, 100, 1));

        numB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        numB.setModel(new javax.swing.SpinnerNumberModel(0, -100, 100, 1));

        numC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        numC.setModel(new javax.swing.SpinnerNumberModel(0, -100, 100, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblExA)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7)
                        .addComponent(lblExB)
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addComponent(lblExC)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExA)
                    .addComponent(jLabel7)
                    .addComponent(lblExB)
                    .addComponent(jLabel9)
                    .addComponent(lblExC)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(btnCalc)
                    .addComponent(numA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(panOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
    //Captando os valores de A,B e C
        int A = Integer.parseInt(numA.getValue().toString());
        int B = Integer.parseInt(numB.getValue().toString());
        int C = Integer.parseInt(numC.getValue().toString());
        double root1 = 0,root2 = 0;
        String desc;
        boolean r;
    //Fazer a checcagem se os valores são válidos
    
    
    // Calcular o Delta
        double delta = Math.pow(B,2) -4 * A * C;
    //Verificar o tipo de raiz que a equação terá
        if (delta < 0){
            //Nenhuma raiz real
            desc="Essa equação não tem nenhuma raiz real";
            r = false;
        }else{
            if (delta > 0){
            //Duas raizes reais
            //Adicionando a descrição
                desc="Essa equação tem duas raízes reais";
            //Calculando as raízes
                root1 = (-B + delta)/2*A;
                root2 = (-B - delta)/2*A;
                r=true;
            }else{
            //Uma raiz real
            //Adicionando a descrição
                desc="Essa equação tem uma raiz real";
            //Calculando as raízes
                root1 = (-B + delta)/2*A;
                root2 = root1;
                r=true;
            }
        }
    //Atribuindo o resultado
        String out1 = r==true?Double.toString(root1):"Inexistente";
        String out2 = r==true?Double.toString(root2):"Inexistente";
        lblOutDesc.setText(desc);
        lblOutPos.setText(out1);
        lblOutNeg.setText(out2);
    //Mostrando o resultado
        panOut.setVisible(true);
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblExA;
    private javax.swing.JLabel lblExB;
    private javax.swing.JLabel lblExC;
    private javax.swing.JLabel lblOutDesc;
    private javax.swing.JLabel lblOutNeg;
    private javax.swing.JLabel lblOutPos;
    private javax.swing.JSpinner numA;
    private javax.swing.JSpinner numB;
    private javax.swing.JSpinner numC;
    private javax.swing.JPanel panOut;
    // End of variables declaration//GEN-END:variables
}
