/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package francisleysalla.calculadoradelta;

/**
 *
 * @author Francisco
 */
public class Calculadora extends javax.swing.JFrame {
    int A = 0,B = 0,C = 0;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        panOut.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numA = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        numB = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        numC = new javax.swing.JSpinner();
        btnCalc = new javax.swing.JButton();
        panOut = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        lblRoot = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblOutB = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOutA = new javax.swing.JLabel();
        lblOutC = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Deltas");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 0, 0));
        jLabel1.setText("A:");

        numA.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        numA.setModel(new javax.swing.SpinnerNumberModel());
        numA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numAStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 0, 0));
        jLabel2.setText("B:");

        numB.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        numB.setModel(new javax.swing.SpinnerNumberModel());
        numB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numBStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(115, 0, 0));
        jLabel3.setText("C:");

        numC.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        numC.setModel(new javax.swing.SpinnerNumberModel());
        numC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numCStateChanged(evt);
            }
        });

        btnCalc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalc.setText("<html>Calcular &Delta;</html>");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("<html>&Delta; =</html>");

        lblRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRes.setForeground(new java.awt.Color(115, 0, 0));
        lblRes.setText("Resultado");

        lblRoot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRoot.setForeground(new java.awt.Color(115, 0, 0));
        lblRoot.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRoot.setText("Raizes da equação");

        javax.swing.GroupLayout panOutLayout = new javax.swing.GroupLayout(panOut);
        panOut.setLayout(panOutLayout);
        panOutLayout.setHorizontalGroup(
            panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
            .addGroup(panOutLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panOutLayout.setVerticalGroup(
            panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOutLayout.createSequentialGroup()
                .addGroup(panOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRes))
                .addGap(15, 15, 15)
                .addComponent(lblRoot))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("<html>&Delta; = </html>");

        lblOutB.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblOutB.setForeground(new java.awt.Color(115, 0, 0));
        lblOutB.setText("B");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("² - 4 . ");

        lblOutA.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblOutA.setForeground(new java.awt.Color(115, 0, 0));
        lblOutA.setText("A");

        lblOutC.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblOutC.setForeground(new java.awt.Color(115, 0, 0));
        lblOutC.setText("C");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCalc, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblOutB)
                                    .addGap(0, 0, 0)
                                    .addComponent(jLabel6)
                                    .addGap(0, 0, 0)
                                    .addComponent(lblOutA)
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel9)
                                    .addGap(5, 5, 5)
                                    .addComponent(lblOutC)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(numB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(numC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOutB)
                    .addComponent(jLabel6)
                    .addComponent(lblOutA)
                    .addComponent(lblOutC)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        /*
            Capture the information
            Calculate the delta
            Show the delta
            See how may roots it has
            Show that
        
            
        */
        //Calculate and show Delta
        double delta = Math.pow(B,2) -4 * A * C;
        lblRes.setText(Double.toString(delta));
        //How many roots it has?
        if(delta > 0){
            // Two roots
            lblRoot.setText("Há duas raízes reais");
        }else{
            if (delta == 0){
                //One root
                lblRoot.setText("Há uma raiz real");
            }else{
                //No root
                lblRoot.setText("Não existem raízes reais");
            }
        }
        
        //Show the result
        panOut.setVisible(true);
    }//GEN-LAST:event_btnCalcActionPerformed

    
   
    private void numBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numBStateChanged
        // TODO add your handling code here:
        B = Integer.parseInt(numB.getValue().toString());
        lblOutB.setText(Integer.toString(B));
    }//GEN-LAST:event_numBStateChanged

    private void numCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numCStateChanged
        // TODO add your handling code here:
        C = Integer.parseInt(numC.getValue().toString());
        lblOutC.setText(Integer.toString(C));
    }//GEN-LAST:event_numCStateChanged

    private void numAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numAStateChanged
        // TODO add your handling code here:
        A = Integer.parseInt(numA.getValue().toString());
        lblOutA.setText(Integer.toString(A));
    }//GEN-LAST:event_numAStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblOutA;
    private javax.swing.JLabel lblOutB;
    private javax.swing.JLabel lblOutC;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblRoot;
    private javax.swing.JSpinner numA;
    private javax.swing.JSpinner numB;
    private javax.swing.JSpinner numC;
    private javax.swing.JPanel panOut;
    // End of variables declaration//GEN-END:variables
}
